name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Restore users file
        run: |
          echo "${{ secrets.USERS_JSON_B64 }}" | base64 --decode > users.json

      - name: Terraform Init
        working-directory: ./terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform init -reconfigure

      - name: Try to unlock Terraform state
        continue-on-error: true
        run: |
          echo "Attempting to unlock Terraform state..."
          terraform -chdir=terraform force-unlock -force eb0c4f51-f20b-f819-43ca-d516721bd612 || echo "No existing lock found"

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_ssh_public_key: ${{ secrets.SSHKEY }}
          TF_VAR_username: ${{ secrets.USERNAME }}
        run: terraform destroy -auto-approve -lock-timeout=60s
